# https://taskfile.dev
version: '3'
vars:
  BINFILE: eph

includes:
  dev: ./Taskfile_dev.yml

tasks:
  default:
    desc: "List tasks"
    cmds:
      - task -a

  build:
    desc: "Build the binary"
    cmds:
      - CGO_ENABLED=0 go build -ldflags '-w -s' -o {{.BINFILE}} .

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean

  godoc:
    desc: "Run godoc server"
    cmds:
      - godoc -http=:6060

  tests:
    desc: "Run the tests"
    dir: tests
    preconditions:
      - test -f env.yml
    cmds:
      - venom run integration.yml --var-from-file env.yml --output-dir="log" --stop-on-failure
